# 配置端口
server:
  port: 8888

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.26.63.165:3306/paas?useUnicode=true&characterEncoding=utf-8
    username: mysqluser
    password: mysqluser
    type: com.alibaba.druid.pool.DruidDataSource
  # velocity
  velocity:
    resource-loader-path: /

# mybatis-plus相关配置
mybatis-plus:
  type-aliases-package: com.wake.generator.infra.*.repository.model
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# the storage type, you can config oss(Aliyun),cos(Tencent),obs(Huawei),s3(Amazon)
storage:
  type: cos

tencent:
  cos:
    internalEndpoint: ap-guangzhou
    endpoint: ap-guangzhou
    accessKeyId: AKID75oNhmI8xYsxxhcVYMwHKDqEPL1SBcRB
    accessKeySecret: f4E9pGRTGn8D3dy63kCTTEk13vYv50e2
    bucket-configs:
      - key: material
        readPermission: public
        name: test-material-1259575047
        cdnUrl:
        isDefault: false