# resources/templates/core.yml
templates:
  - type: "AGGREGATE"
#    dependencies: ["VALUE_OBJECT"]
    description: 聚合根模板
    template: "/newTemplates/aggregate.vm"
    output: "src/main/java/${package}/${className}.java"
    variables:
      - target: "package"
        source: "${rootPackage}/domain"
      - target: "className"
        source: "${name}"
      - target: "fields"
    subTemplates:
      - type: "REPOSITORY"
        description: 聚合根-仓储接口模板
        enabled: false
        template: "/newTemplates/repository.vm"
        output: "src/main/java/${package}/${className}.java"
        variables:
          - target: "package"
            source: "${rootPackage}/domain"
          - target: "className"
            source: "${name}Repository"

  - type: "ENTITY"
    description: 实体模板
    template: "/newTemplates/entity.vm"
    output: "src/main/java/${package}/${className}.java"
    variables:
      - target: "package"
        source: "${rootPackage}/domain"
      - target: "className"
        source: "${name}"

  - type: "VALUE_OBJECT"
    description: 值对象模板
    template: "/newTemplates/valueObject.vm"
    output: "src/main/java/${package}/${className}.java"
    variables:
      - target: "package"
        source: "${rootPackage}/domain"
      - target: "className"
        source: "${name}"