package com.wakedt.visual.start.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2WebMvc;

@Configuration
@EnableSwagger2WebMvc
public class Knife4jConfiguration {

    ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("DDD可视化开发平台")
                .description("DDD可视化开发平台\n\nIDEA代码生成插件接入文档：\nhttp://www.wakedata.net/pages/viewpage.action?pageId=34999420 (generated by visual-ddd generator)")
                .license("")
                .licenseUrl("https://unlicense.org")
                .termsOfServiceUrl("")
                .version("0.0.1-SNAPSHOT")
                .contact(new Contact("开发云", "https://ddd.wakedt.cn", ""))
                .build();
    }

    @Bean
    public Docket customImplementation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.wakedt.visual"))
                .build()
                .apiInfo(apiInfo());
    }

}