# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          maven-version: '3.6.3'

      - name: Configure settings.xml
        run: |
          mkdir -p $HOME/.m2
          echo "<settings><servers><server><id>github</id><username>USERNAME</username><password>TOKEN</password></server></servers></settings>" > $HOME/.m2/settings.xml
          sed -i 's/USERNAME/${{ secrets.GITHUB_USERNAME }}/g' $HOME/.m2/settings.xml
          sed -i 's/TOKEN/${{ secrets.GITHUB_TOKEN }}/g' $HOME/.m2/settings.xml

      - name: Build and deploy
        run: mvn deploy